In [2]:
import boto3
from botocore import UNSIGNED
from botocore.config import Config
import os
import json

import pandas as pd
import re
import numpy as np
from sqlalchemy import create_engine, text

In [25]:
bucket_name = "data-analyst-home-assignment"
local_path = "/Users/saule/Documents"

s3 = boto3.client('s3', config=Config(signature_version=UNSIGNED))

paginator = s3.get_paginator('list_objects_v2')
pages = paginator.paginate(Bucket=bucket_name)

for page in pages:
    for obj in page.get('Contents', []):
        key = obj['Key']
        dest_path = os.path.join(local_path, key)
        
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        
        print(f"Downloading {key} to {dest_path} ...")
        s3.download_file(bucket_name, key, dest_path)

print("All files downloaded!")

Downloading messages.json to /Users/saule/Documents/messages.json ...
Downloading priority.json to /Users/saule/Documents/priority.json ...
Downloading reputations.json to /Users/saule/Documents/reputations.json ...
Downloading true_reputations.json to /Users/saule/Documents/true_reputations.json ...
All files downloaded!

In [3]:
df_messages = pd.read_json('/Users/saule/Documents/messages.json')

In [3]:
df_messages.head()

,id,url,date,source,protocol,response_code,load_time_seconds,domain_age_years,page_size_kb,redirects,service
0,e4c75faf-2647-499d-bec0-3602b21c17c4,news.mail.ru,2022-12-11,source_2,HTTP,200.0,1.87,2.0,252,False,service_2
1,1a4d5919-5e55-4730-a2b7-dfe46490c03e,rs6.net,2024-02-15,source_4,HTTP,200.0,0.59,2.0,179,False,service_2
2,59d6d211-9533-41de-b290-bc996d042b06,postfinance.ch,2020-04-20,source_1,HTTPS,200.0,2.10,1.0,252,False,service_3
3,1fd98cc8-25f7-4328-8764-21e046214e90,libero.it,2020-05-29,source_1,HTTP,200.0,9.65,2.0,308,"[True, pandora.com]",service_4
4,9d2d879a-b9f9-4839-9dab-bd6d96ed8a30,xvideos.es,2022-01-30,source_4,HTTP,200.0,9.07,1.0,80,"[True, pravda.com.ua]",service_3

In [11]:
df_priority = pd.read_json('/Users/saule/Documents/priority.json')
df_priority.head()

                                     id   priority  timestamp
0  e81bbb34-b37d-4055-8356-27aa1f179c4d  service_4 2023-12-26
1  5f5d8e39-5539-4503-a07e-a748cc2adffb  service_4 2023-08-28
2  f2667858-92e4-40e7-91e9-df2c32ab4079  service_3 2023-02-26
3  6b99aaf9-847e-45ad-9eb3-8e8448dd0fca  service_3 2020-05-16
4  385c2534-bc68-40f8-985f-d6f39ddb8b9a  service_1 2021-02-03

In [12]:
df_reputations = pd.read_json('/Users/saule/Documents/reputations.json')
df_reputations.head()

,id,reputation_source,reputation_score,reputation_category,reputation_date
0,b5ef91f1-2cad-4c68-b150-ab3772f5d998,source_2,87,neutral,2023-08-20
1,a06064f8-71d0-44ee-8630-56a81c5ac16f,source_3,57,good,2024-02-05
2,551fa742-7fc5-42d1-88fa-1a93387f0eb2,source_2,75,good,2021-08-05
3,99de4aec-7070-4d75-9970-c7d5809b6438,source_3,66,neutral,2023-02-22
4,13d3fbb4-bc17-485c-b4f4-266268c7fe83,source_1,70,good,2020-04-19

In [13]:
df_true_reputations =  pd.read_json('/Users/saule/Documents/true_reputations.json')
df_true_reputations.head()

,id,true_reputation,reputation_source,timestamp
0,356768e7-eb3c-4b0d-8bdd-975ec605e1ec,clean,service_C,2020-06-18
1,33e1be2d-bc22-4771-ac98-f717714a9b5c,clean,service_A,2023-04-13
2,deac4684-3fcc-4159-800a-988d88af475e,unknown,service_B,2020-10-18
3,50f5f3e8-a3a2-491f-baa2-bf6557ee481a,malware,service_D,2022-07-29
4,dbe9ff6e-18ca-41c3-908f-b50a98f28249,clean,service_D,2023-03-09

In [3]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/mysql")

with engine.connect() as conn:
    result = conn.execute(text("SELECT user(), version();"))
    print(result.fetchall())

[('root@localhost', '9.4.0')]

In [4]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306")
database = 'nordsec'
with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {database};"))
    print(f"Database {database} created.")

✅ Database 'nordsec' created.

In [7]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/nordsec")

In [19]:
df_priority.to_sql("priority", con=engine, if_exists="replace", index=False)

100000

In [15]:
df_reputations.to_sql('reputations', con=engine, if_exists="replace", index=False)

90000

In [16]:
df_true_reputations.to_sql('true_reputations', con=engine, if_exists="replace", index=False)

93334

In [5]:
for col in df_messages.columns:
    print(col, df_messages[col].apply(type).unique())

id [<class 'str'>]
url [<class 'str'>]
date [<class 'pandas._libs.tslibs.timestamps.Timestamp'>]
source [<class 'str'>]
protocol [<class 'str'>]
response_code [<class 'float'>]
load_time_seconds [<class 'float'>]
domain_age_years [<class 'float'>]
page_size_kb [<class 'int'>]
redirects [<class 'bool'> <class 'list'>]
service [<class 'str'>]

In [6]:
df_messages['response_code'] = df_messages['response_code'].astype('Int64')
df_messages['domain_age_years'] = df_messages['domain_age_years'].astype('Int64')

In [7]:
def count_redirects(val):
    if isinstance(val, list):
        return sum(isinstance(item, str) for item in val)

    return 0

df_messages['redirect_count'] = df_messages['redirects'].apply(count_redirects)

In [8]:
df_messages['redirects'] = df_messages['redirects'].apply(
    lambda x: json.dumps(x) if isinstance(x, list) else x
)

In [9]:
def safe_serialize(val):
    if isinstance(val, list):
        return json.dumps(val)
    elif isinstance(val, dict):
        return json.dumps(val)
    else:
        return val

df_messages['redirects'] = df_messages['redirects'].apply(safe_serialize)

In [10]:
df_messages.head()

,id,url,date,source,protocol,response_code,load_time_seconds,domain_age_years,page_size_kb,redirects,service,redirect_count
0,e4c75faf-2647-499d-bec0-3602b21c17c4,news.mail.ru,2022-12-11,source_2,HTTP,200,1.87,2,252,False,service_2,0
1,1a4d5919-5e55-4730-a2b7-dfe46490c03e,rs6.net,2024-02-15,source_4,HTTP,200,0.59,2,179,False,service_2,0
2,59d6d211-9533-41de-b290-bc996d042b06,postfinance.ch,2020-04-20,source_1,HTTPS,200,2.10,1,252,False,service_3,0
3,1fd98cc8-25f7-4328-8764-21e046214e90,libero.it,2020-05-29,source_1,HTTP,200,9.65,2,308,"[true, ""pandora.com""]",service_4,1
4,9d2d879a-b9f9-4839-9dab-bd6d96ed8a30,xvideos.es,2022-01-30,source_4,HTTP,200,9.07,1,80,"[true, ""pravda.com.ua""]",service_3,1

In [12]:
df_messages.to_sql('messages', con=engine, if_exists="replace", index=False)

100000

In [4]:
df_messages_redirects = df_messages.copy()

redirect_rows = []

for idx, row in df_messages_redirects.iterrows():
    redirects = row['redirects']
    msg_id = row['id']
    
    if not isinstance(redirects, list):
        continue
    
    domains = redirects[1:] if redirects[0] is True else redirects
    
    for order, domain in enumerate(domains, start=1):
        redirect_rows.append({
            'message_id': msg_id,
            'redirect_order': order,
            'redirect_domain': domain
        })

df_redirects = pd.DataFrame(redirect_rows)

In [5]:
df_redirects.head()

                             message_id  redirect_order redirect_domain
0  1fd98cc8-25f7-4328-8764-21e046214e90               1     pandora.com
1  9d2d879a-b9f9-4839-9dab-bd6d96ed8a30               1   pravda.com.ua
2  62650a11-ff8b-4638-b858-060874194ce8               1   google.com.co
3  62650a11-ff8b-4638-b858-060874194ce8               2    docusign.com
4  ab190659-2b1a-4531-9ca5-279beeedc2d1               1  fatalmodel.com

In [8]:
df_redirects.to_sql('redirects', con=engine, if_exists="replace", index=False)

50056